[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "geopandas>=1.1.1",
    "pandas>=2.3.2",
    "shapely>=2.1.2",
    "tqdm>=4.67.1",
]
