[project]
name = "lstm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.1",
    "torch>=2.8.0",
    "matplotlib>=3.7.0",
]
